[tool.poetry]
name = "swole-bot"
version = "0.1.0"
description = "An AI bot using RAG to help users get swole ğŸ’ªğŸ»"
authors = ["Alex <alex@leetsoftware.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.10"
python-dotenv = "1.0.0"
requests = "2.31.0"
tqdm = "4.66.1"
chromadb = "0.4.22"
llama-index = "0.10.1"
openai = "1.12.0"
urllib3 = "2.2.0"
transformers = "4.36.2"
torch = "2.1.2"
sentence-transformers = "2.2.2"
pandas = "2.1.4"
backoff = "2.2.1"

[tool.poetry.group.dev.dependencies]
black = "24.2.0"
isort = "5.13.2"
flake8 = "7.0.0"
pytest = "8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
app = "main:main"
